# api-gateway
#
# VERSION               1.0.0

## 指定基础镜像
FROM fintech-centos7.6-java:1.8.0_221

## 标签标识
LABEL department="fintech_java"
LABEL description="基础镜像"

##用户
USER ufintech

## 复制文件到镜像
#ADD jdk-8u221-linux-x64.tar.gz /opt/jdk-8u221-linux-x64.tar.gz
ADD --chown=ufintech:ufintech api-gateway/target/api-gateway-1.0.0.jar /data/app

## 在基础镜像基础上启动执行以下命令并提交保存
#RUN mkdir logs

## 设置环境变量
ENV JAVA_HOME=/opt/jdk1.8.0_221
ENV PATH=$PATH:$JAVA_HOME/bin
ENV TZ="Asia/Shanghai"
ENV LANG="en_US.UTF-8"

## 开放端口
EXPOSE 9018

## 挂载匿名卷，
VOLUME /data/app

## 指定程序工作目录
WORKDIR /data/app/

## 程序启动命令
ENTRYPOINT ["java"]
CMD    ["-Xrs","-Xmx512m","-jar", "api-gateway-1.0.0.jar"]
