#logging.level.root: DEBUG
logging.level.org.springframework: DEBUG


#文件写入磁盘的阈值
spring.servlet.multipart.file-size-threshold: 0
# 最大文件大小
spring.servlet.multipart.max-file-size: 100MB
# 最大请求大小
spring.servlet.multipart.max-request-size: 200MB

spring.cloud.bus.trace.enabled: true

# 开启监控接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
        #include: refresh,health,info #打开部分