server.port: 2000
spring.application.name: eureka_server  # 其他服务指定Service-Id是需要用大写, 控制台显示的也是大写 
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false #Eureka默认使用 hostname 进行服务注册: eg."DESKTOP-G3BHFUS:eureka_server:2000"， 以IP地址注册到服务中心，相互注册使用IP地址
    instance-id:  186.198.7.24:2300   #指定向注册中心注册的服务ip地址。 ip地址也可以是"http://域名地址"(http://eureka.com). eureka后台在status处会显示这个，但访问还是取的真实IP
    lease-renewal-interval-in-seconds: 30 #  服务续约任务的调用间隔时间，默认为30秒
    lease-expiration-duration-in-seconds: 90 # renew续约时更新lastUpdateTimestamp = currentTimeMillis + 这个duration时间
  client:
    registerWithEureka: true  #将自己注册到EurekaServer
    fetchRegistry: true
    healthcheck.enabled: true
    serviceUrl:
        defaultZone:  http://localhost:2100/eureka/,http://localhost:2000/eureka/ #高可用 互相注册
  server:
    enable-self-preservation: true #自我保护，
    eviction-interval-timer-in-ms: 10000 # 失效实例检测任务调度间隔
#开启@FeignClient的fallback   
feign:
    hystrix:
        enabled: true
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000  

smsEnv: dev

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 15000

    # 默认显示的是： 主机名：应用名：应用端口
    # ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}},
    #http://localhost:2100/eureka/apps 能看到具体的ip地址